// Builds THIRD_PARTY_NOTICES.md and src/lib/licenses.generated.json from the production
// dependency tree, plus the code and fonts that don't come with a license file in npm.
// Run after adding or updating dependencies: npm run notices
import { execFileSync } from "node:child_process";
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const npm = process.platform === "win32" ? "npm.cmd" : "npm";

// Every installed production package (one per line), skipping the project itself.
const paths = execFileSync(npm, ["ls", "--omit=dev", "--all", "--parseable"], { cwd: root, encoding: "utf8" })
  .split("\n")
  .slice(1)
  .filter(Boolean);

const LICENSE_FILE = /^(licen[cs]e|copying)(\.(md|txt))?$/i;
// In short permissive licenses only the copyright lines differ between packages, so those
// lines are kept per package and the shared body is printed once. Anything else stays whole.
const SHORT = new Set(["MIT", "ISC", "BSD-2-Clause", "BSD-3-Clause", "0BSD"]);
// A notice line, not a sentence like "copyright notice and this permission notice…".
const COPYRIGHT = /^\s*(Copyright|COPYRIGHT|\([cC]\)|©)\s*(\([cC]\)|©)?\s*[\d[A-Z]/;

const pkgs = new Map();
for (const dir of [...new Set(paths)]) {
  const pkg = JSON.parse(readFileSync(join(dir, "package.json"), "utf8"));
  // Prebuilt binaries for one OS/CPU (sharp's libvips, the SWC compiler) differ per machine
  // and run only on the server; see the note in the output. Type packages never ship.
  if (pkg.os || pkg.cpu || pkg.name.startsWith("@types/")) continue;
  if (pkgs.has(pkg.name)) continue;
  const file = readdirSync(dir).find((f) => LICENSE_FILE.test(f));
  pkgs.set(pkg.name, {
    name: pkg.name,
    version: pkg.version,
    license: pkg.license ?? "See package",
    text: file ? readFileSync(join(dir, file), "utf8") : null,
  });
}

// Pretendard's npm package has no license file; use the upstream OFL text.
pkgs.get("pretendard").text = readFileSync(join(root, "licenses/pretendard-OFL-1.1.txt"), "utf8");
// shadcn/ui is copied into src/components/ui rather than installed.
pkgs.set("shadcn/ui", {
  name: "shadcn/ui",
  version: "component source, adapted",
  license: "MIT",
  text: readFileSync(join(root, "licenses/shadcn-ui-MIT.md"), "utf8"),
});

// The standard MIT body (from shadcn/ui's file) for MIT packages that ship no license file.
const MIT_BODY = readFileSync(join(root, "licenses/shadcn-ui-MIT.md"), "utf8")
  .split("\n")
  .filter((l) => !COPYRIGHT.test(l) && !/^MIT License/.test(l))
  .join("\n")
  .trim();

// Group packages by license body (copyright lines removed); keep each package's own lines.
const groups = new Map();
for (const p of [...pkgs.values()].sort((a, b) => a.name.localeCompare(b.name))) {
  const lines = (p.text ?? "").replace(/\r\n/g, "\n").split("\n");
  const copyright = lines.filter((l) => COPYRIGHT.test(l)).map((l) => l.trim());
  const body = lines
    .filter((l) => !COPYRIGHT.test(l))
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
  // Longer licenses (Apache, OFL with its Reserved Font Names, CC) stay exactly as shipped.
  const keepWhole = !SHORT.has(p.license) && p.text !== null;
  const text = keepWhole ? p.text.trim() : p.text === null && p.license === "MIT" ? MIT_BODY : body;
  const key = `${p.license}:${text.replace(/\s+/g, " ")}`;
  if (!groups.has(key)) groups.set(key, { license: p.license, text, packages: [] });
  groups.get(key).packages.push({ name: p.name, version: p.version, copyright: keepWhole ? [] : copyright });
}
const list = [...groups.values()].sort((a, b) => b.packages.length - a.packages.length || a.license.localeCompare(b.license));

const NOTE =
  "Platform-specific prebuilt binaries are not listed one by one: sharp's native build " +
  "(Apache-2.0) with libvips (LGPL-3.0-or-later), and the Next.js SWC compiler (MIT). They run " +
  "only on the server or at build time and are never sent to your device.";

writeFileSync(
  join(root, "src/lib/licenses.generated.json"),
  JSON.stringify({ note: NOTE, groups: list }, null, 1) + "\n",
);

let md = "# Third-party notices\n\nGenerated by `npm run notices` from the production dependencies. Do not edit by hand.\n\n";
md += `${NOTE}\n\n`;
for (const g of list) {
  md += `## ${g.license}\n\n`;
  for (const p of g.packages) {
    md += `- ${p.name} ${p.version}${p.copyright.length ? ` — ${p.copyright.join("; ")}` : ""}\n`;
  }
  md += g.text ? `\n\`\`\`\n${g.text}\n\`\`\`\n\n` : "\n(No license file in the package; license as declared in its package.json.)\n\n";
}
writeFileSync(join(root, "THIRD_PARTY_NOTICES.md"), md);

const missing = list.filter((g) => !g.text).flatMap((g) => g.packages.map((p) => p.name));
console.log(`${pkgs.size} packages, ${list.length} license texts.${missing.length ? ` No license file: ${missing.join(", ")}` : ""}`);
